#include <stdio.h>
#include <stdlib.h>
#include <stdalign.h>
#include <string.h>
#include <ctype.h>
#include <stddef.h>
#include <time.h>
#include "scan.c"
#include "grade_number.c"
#include "woman_brillant_am.c"
#include "woman_good_am.c"
#include "woman_pass_am.c"
#include "woman_fail_am.c"
#include "woman_scholar_am.c"
#include "woman_brillant_pm.c"
#include "woman_good_pm.c"
#include "woman_pass_pm.c"
#include "woman_fail_pm.c"
#include "woman_scholar_pm.c"
#include "man_scholar_am.c"
#include "man_scholar_pm.c"
#include "man_brillant_am.c"
#include "man_brillant_pm.c"
#include "man_good_am.c"
#include "man_good_pm.c"
#include "man_pass_am.c"
#include "man_pass_pm.c"
#include "man_fail_am.c"
#include "man_fail_pm.c"