

void man_p_married_good()
{
  printf("%s\nGood noon Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight his way to the top. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in India.You are a great man and I am so sure you'd be of great service to your wife. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_engaged_good()
{
  printf("%s\nGood noon Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight his way to the top. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in India.You are a great man and I am so sure you'd be of great service to your soon to be wife. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_complicated_good()
{
  printf("%s\nGood noon Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight his way to the top. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in India.You are a man whom I cherish and admire. can I advice you? You got to go back to your girlfriend and settle whatever differences is between you two.I I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_single_good()
{
  printf("%s\nGood noon Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight his way to the top. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in India.You are a great man.Can I advice you sir? please find yourself a girlfriend. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_other_good()
{
  printf("%s\nGood noon Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight his way to the top. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in India.You are a great man . I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}