

void man_p_married_fail()
{
    printf("%s\nGood morning Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great man and I am so sure you'd be of great service to your wife. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_engaged_fail()
{
    printf("%s\nGood morning Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great man and I am so sure you'd be of great service to your soon to be wife. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_complicated_fail()
{
    printf("%s\nGood morning Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a man whom I cherish and admire. can I advice you? You got to go back to your girlfriend and settle whatever differences is between you two.I I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_single_fail()
{
    printf("%s\nGood morning Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great man.Can I advice you sir? please find yourself a girlfriend. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void man_p_other_fail()
{
    printf("%s\nGood morning Mr %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great man . I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}