

void woman_married_fail()
{
    printf("%s\nGood Morning Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great woman and I am so sure you'd be of great service to your husband. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_engaged_fail()
{
    printf("%s\nGood Morning Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great woman and I am so sure you'd be of great service to your soon to be husband. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_complicated_fail()
{
    printf("%s\nGood Morning Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a man whom I cherish and admire. can I advice you? You got to go back to your boyfriend and settle whatever differences is between you two.I I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_single_fail()
{
    printf("%s\nGood Morning Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great woman.Can I advice you ma'am? please find yourself a boyfriend. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_other_fail()
{
    printf("%s\nGood Morning Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You need to believe in yourself. As we have seen so far you graduated with %.2f in %s department which is a %c from the university of %s. poor! You were born in %s which means you are %i years old. We are not interested in you due to your poor academical performance so we won't be giving you the scholarship.You are a great woman . I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
