

void woman_p_married_brillant()
{
    printf("%s\nGood noon Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight her way to the top. As we have seen so far you graduated with %.2f in %s department which is %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in Australia.You are a good woman and I am so sure you'd be of great service to your husband. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_p_engaged_brillant()
{
    printf("%s\nGood noon Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight her way to the top. As we have seen so far you graduated with %.2f in %s department which is %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in Australia.You are a good woman and I am so sure you'd be of great service to your soon to be husband. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_p_complicated_brillant()
{
    printf("%s\nGood noon Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight her way to the top. As we have seen so far you graduated with %.2f in %s department which is %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in Australia.You are a woman whom I cherish alot and admire. can I advice you? You got to go back to your boyfriend and settle whatever differences is between you two.I I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_p_single_brillant()
{
    printf("%s\nGood noon Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight her way to the top. As we have seen so far you graduated with %.2f in %s department which is %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in Australia.You are a good woman.Can I advice you ma'am? please find yourself a boyfriend. I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}
void woman_p_other_brillant()
{
    printf("%s\nGood noon Miss %s-%s, I am glad to welcome you to Yongee B online Session. Based on the information given to us by the computer system, we found out that your City is situated in %s we were able to track your current location to %s. You are a person with great character who is willing to learn and fight her way to the top. As we have seen so far you graduated with %.2f in %s department which is %c from the university of %s. Great! You were born in %s which means you are %i years old. We are very interested in you which is why we are giving you a scholarship visa to study in Australia.You are a good woman . I love the nickname %s. For more info email me @%s", info.check, info.Name, info.Surname, info.State, info.currentLocation, info.Cgpa, info.Department, info.Grade, info.collegeName, info.D_O_B, info.Age, info.Nickname, info.Email);
}